### ISSUE TITLE
Problem getting UI to display data from tf profiler

### ISSUE THREAD

**Issue by David-Levinthal** [tensorflow/profiler-ui#1]
I added code to the NMT train.py script. I have run the NMT trainer many times, it works fine. This created a profile
  with tf.contrib.tfprof.ProfileContext('/home/levinth/train_dir') as pctx:
    while global_step < num_train_steps:
      ### Run a step ###
      start_time = time.time()
      try:
        step_result = loaded_train_model.train(train_sess)
        (_, step_loss, step_predict_count, step_summary, global_step,
         step_word_count, batch_size) = step_result
        hparams.epoch_step += 1
      except tf.errors.OutOfRangeError:
etc..etc
 ls -l ~/train_dir/
total 52688
-rw-rw-r-- 1 levinth levinth  8912664 Mar  8 11:43 profile_100
-rw-rw-r-- 1 levinth levinth     5977 Mar  8 12:11 timeline_100_100
-rw-rw-r-- 1 levinth levinth 45030165 Mar  8 12:11 timeline_100_11

installed go, used that to install pprof
set PYTHONPATH to my install of the R1.5 wheel built for cuda9.1, libcudnn7.0.4 and python2
I have to maintain many versions of TF due to limitations of assorted applications
export PYTHONPATH=~/tf_r1.5_c91_py2/
and remove the requirement on tf r1.4.1 from the requirements.txt
then did the pip install
pip install --user -r requirements.txt

invoking ui.py did the following
python ui.py --profile_context_path=/home/levinth/train_dir/profile_100
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
 * Running on http://0.0.0.0:7007/ (Press CTRL+C to quit)
127.0.0.1 - - [08/Mar/2018 13:33:26] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/Mar/2018 13:33:26] "GET /static/js/app.js?ts=1520544806.33 HTTP/1.1" 200 -
127.0.0.1 - - [08/Mar/2018 13:33:26] "GET /static/css/style.css?ts=1520544806.33 HTTP/1.1" 200 -
127.0.0.1 - - [08/Mar/2018 13:33:27] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/Mar/2018 13:33:27] "GET /static/css/style.css?ts=1520544807.2 HTTP/1.1" 200 -
127.0.0.1 - - [08/Mar/2018 13:33:27] "GET /static/js/app.js?ts=1520544807.2 HTTP/1.1" 200 -
127.0.0.1 - - [08/Mar/2018 13:33:27] "GET /static/images/tf-400.png HTTP/1.1" 200 -
the gui came up but I could not get it to display anything
any assistance would be greatly appreciated

**Comment by David-Levinthal** [comment]
AHHHH..firefox was my default browser and that does not work
When I opened
http://0.0.0.0:7007
in a chrome browser (the ui.py was still running)..suddenly it all worked
It might be good to explain that the tool only works with chrome

**Comment by ChrisAntaki** [comment]
Thanks for the heads up, David! I'll investigate why it's not working with FF

**Comment by David-Levinthal** [comment]
This may have to do with the tool needing the chrome tracer..which does not
exist in other browsers..
this may be just a documentation issue therefore
:-)

**Comment by ChrisAntaki** [comment]
The documentation has been updated. Thanks again for pointing this out, David.
