### ISSUE TITLE
can not produce context file

### ISSUE THREAD

**Issue by liaocz** [tensorflow/profiler-ui#12]
I use tf.contrib.tfprof.ProfileContext as follows, but it can not produce any context file

```
with tf.contrib.tfprof.ProfileContext('./test') as pctx:
       train(model, train_data_files, val_data_file)
```

how to soloved it ? 
thanking you very much~

**Comment by liaocz** [comment]
when i use `with tf.contrib.tfprof.ProfileContext('./test', dump_steps=[4]) as pctx:` it can produce profile_4 file, but it arised following error:
`python ui.py --profile_context_path=/home/test/profile_4`

UnboundLocalError: local variable 'path' referenced before assignment

**Comment by ChrisAntaki** [comment]
Thanks for reporting this! Could you report the issue in the https://github.com/tensorflow/tensorflow repository? This repository is just for the UI
