### ISSUE TITLE
Profiled time for one step higher than in actual training

### ISSUE THREAD

**Issue by gaganbahga** [tensorflow/profiler-ui#13]
The time taken for one step of training as profiled by the profiler is much higher than how much time one step takes during actual training. For example, for my model the profiler shows that one training step takes around 4 second to complete, however in the actual training, a training step on an average takes less than 1 second.
Please note that I am not referring to the slowdown of the tensorflow during profiling.
I am wondering what is the reason for this. One hypothesis that I have is that during actual training, many ops get performed in parallel where as profiler probably just adds up the time of each individual operation to report the total time?

**Comment by ChrisAntaki** [comment]
Thanks for reporting this! Could you report the issue in the https://github.com/tensorflow/tensorflow repository? This repository is just for the UI
