### ISSUE TITLE
Problem getting UI working

### ISSUE THREAD

**Issue by theyiwenliu** [tensorflow/profiler-ui#3]
I trigger a training with `with tf.contrib.tfprof.ProfileContext('/tmp/train_dir') as pctx:`
And I tried to launch the UI `python ui.py --profile_context_path=/tmp/train_dir/profile_100`

I did see a warning in terminal otherwise it looked fine:
\* Serving Flask app "server.server" (lazy loading)
 \* Environment: production
    WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 \* Debug mode: off
 \* Running on http://0.0.0.0:7007/ (Press CTRL+C to quit)

And this is the what I saw from the UI `http://0.0.0.0:7007/`:
<img width="1148" alt="screen shot 2018-05-03 at 3 55 27 pm" src="https://user-images.githubusercontent.com/10496910/39606465-7241c932-4eea-11e8-8a6b-79fa973fedd9.png">

Could somebody help me with that? Thanks!

Tensorflow: 1.4.1
Browser: Chrome

**Comment by ChrisAntaki** [comment]
Hey Yi-Wen,

Could you tell me about the environment you're running this command in?

Thanks,
Chris

**Comment by theyiwenliu** [comment]
I was running it within Tensorflow Virtualenv, which has Flask 1.0.2 and Tensorflow 1.4.1.

**Comment by ChrisAntaki** [comment]
Sorry to hear it's not working. Are you running the profiler UI and your web browser on the same machine? Is it possible the profiler UI is running in a VM?

**Comment by theyiwenliu** [comment]
Yes same machine, no VM running.

**Comment by ChrisAntaki** [comment]
Oh, I see. Could you try visiting http://localhost:7007/ when the server is running? If that doesn't work, I'd suggest trying to run the [Flask demo](http://flask.pocoo.org/) locally.

**Comment by ChrisAntaki** [comment]
Just to clarify, I *think* this issue might boil down to figuring out how to access Flask servers running locally on your machine.

**Comment by theyiwenliu** [comment]
@ChrisAntaki [http://localhost:7007/](http://localhost:7007/) works for me! Thanks a lot!

**Comment by ChrisAntaki** [comment]
Nice, glad to help!
