### ISSUE TITLE
Error on request...

### ISSUE THREAD

**Issue by YoungBim** [tensorflow/profiler-ui#5]
Hi Chris !
Just to let you know that I'm facing a similar issue to that of #3  indeed I'm trying to use the UI of tfprof (using google chrome) with the following setup :

**Experiment Side**
conda environment (TLDR: tensorflow-gpu 1.6.0 - python 3.6.4)
[conda_env.txt](https://github.com/tensorflow/profiler-ui/files/2013641/conda_env.txt)
corresponds to the environment in which I run my model and where the file "profile.context" is generated thanks to the pyhtonic line (as stated [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/profiler/README.md)):
`with tf.contrib.tfprof.ProfileContext('/tmp/train_dir') as pctx:`

**Profiling Side**
virtual environment (TLDR: tensorflow 1.6.0 - python 3.6.4)
[venv.txt](https://github.com/tensorflow/profiler-ui/files/2013642/venv.txt)
corresponds to the place where I run the following command:
`python ui.py --profile_context_path=~/path_to_something/profile.context `
obviously I followed your [installation guide](https://github.com/tensorflow/profiler-ui)

**Issue**
The "profile.context" file (real filename is by default profile_100) is effectively generated (weights ~5Mb) only once, at step 100, as I only need one profiling step for now on.
The tfprofiler ui effectivelly opens in google chrome showing all the buttons/scrolling bars/... it should show.
So my issue is that this interface is empty in my case..
- Timeline tab : The server returned an error.
- PPROF : The server seems to be offline.
- Python : Profile was not generated.

Note : FYI there is no VM and all takes place locally on the same machine and I do use Experiment/Estimator APIs.

Sorry for the long post and thanks for reading this !
Cheers

**Comment by ChrisAntaki** [comment]
Hey @YoungBim ! Could you try replacing the `~` with `$HOME` in your command? Ex: `python ui.py --profile_context_path=$HOME/path_to_something/profile.context`

**Comment by YoungBim** [comment]
Ok... I'm fully retarded... thanks for un-blocking me :dancing_men:

**Comment by ChrisAntaki** [comment]
Glad to help! I'll try to improve the error messages as well
